### ISSUE TITLE
structure rule CSIPSTR1 or CSIPISTR4 are fired instead of CSIPSTR10, CSIPSTR11, CSIPSTR12

### ISSUE THREAD

**Issue by ltaimre** [E-ARK-Software/py-rest-ip-validator#14]
Validator treats single representation folder as root folder. Therefore are fired rules regarding root folder (CSIPSTR1 or CSIPSTR4) instead of rules regarding single representation folder (CSIPSTR10, CSIPSTR11, CSIPSTR12)

**Comment by carlwilson** [comment]
Hi @ltaimre can you give a specific link to a package to try, please? A link to the GitHub path would be fine.

**Comment by ltaimre** [comment]
- [CSIPSTR10](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/csip/struct/csipstr10/corpus/structure/CSIPSTR10/IP_18000_CSIPSTR10_1/package). 
A package based on folder structure IP. The 'representations' folder has no subfolder.
Fires CSIPSTR 1 instead of CSIPSTR10

- [CSIPSTR11_1](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/csip/struct/csipstr11/corpus/structure/CSIPSTR11/CSIPSTR11_1/package)
A package based on the folder stucture IP. Sub-folder 'data' named in camelcase
Fires CSIPSTR 1 instead of CSIPSTR11

- [CSIPSTR11_2](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/csip/struct/csipstr11/corpus/structure/CSIPSTR11/CSIPSTR11_2/package)
A package based on the folder stucture IP. Sub-folder 'data' has extra lowercase character in back
Fires CSIPSTR 4 instead of CSIPSTR11

-  [CSIPSTR12_1](https://github.com/DILCISBoard/eark-ip-test-corpus/tree/csip/struct/csipstr12/corpus/structure/CSIPSTR12/IP_18000_CSIPSTR12_1/package)
Fires CSIPSTR 4 instead of CSIPSTR11

**Comment by carlwilson** [comment]
Perfect @ltaimre, thanks very much. Will try to get a fix to you for tomorrow using these to build the unit test suite.

**Comment by carlwilson** [comment]
@ltaimre I'm closing this now as I think the behaviour's as expected. Thanks.
